---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths: {}
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 0.0.0.0:3000
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
